{ config, pkgs, lib, ... }:
let
  cfg = config.modules.nixos.wayland;
  nvidiaCfg = config.modules.nixos.nvidia;
in
{
  options.modules.nixos.wayland = {
    enable = lib.mkEnableOption "Enable Wayland";
  };

  config = lib.mkIf cfg.enable {
    xdg.portal = {
      enable = true;
      wlr.enable = true;
      extraPortals = with pkgs; [
        xdg-desktop-portal-wlr
      ];
      config.common.default = "*"; # possible workaround from version error in nix check
    };

    services = {
      xserver.enable = false; # disable xorg server
      # https://wiki.archlinux.org/title/Greetd
      greetd = {
        enable = true;
        settings = {
          default_session = {
            # Wayland Desktop Manager is installed only for user ryan via home-manager!
            user = "riizu";
            # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
            # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
            command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
            # command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd $HOME/.wayland-session";  # start wayland session with a TUI login manager
          };
        };
      };
    };

    # environment = {
    #   sessionVariables = {
    #     # NIXOS_OZONE_WL = "1"; # Hint electron apps to use wayland
    #     WLR_NO_HARDWARE_CURSORS = "1"; # Fix cursor rendering issue on wlr nvidia.
    #   };
    # };

    # environment.systemPackages = [
    #   (pkgs.waybar.overrideAttrs (oldAttrs: {
    #       mesonFlags = oldAttrs.mesonFlags ++ [ "-Dexperimental=true" ];
    #     })
    #   )

    # ];

    environment.systemPackages = with pkgs; [
    ];
  };
}
